name: "CrossOver"
rng_seed        : 42
num_gpu         : 1
base_dir        : "/drive/dumps/multimodal-spaces/"
exp_dir         : ""
mode            : "train"
naming_keywords : ['task', 'time']

resume : False

logger :
  name : "wandb"
  entity : "multimodal-spaces"

  
data :
  sources     : ['Scannet']
  process_dir : ${base_dir}/preprocess_feats
  
  Scannet:
    base_dir         : /drive/datasets/Scannet
    shape_dir        : /drive/datasets/Shapenet/ShapeNetCore.v2
    process_dir      : ${data.process_dir}/Scannet
    chunked_dir      : ${data.process_dir}/objects_chunked/Scannet
    processor1D      : Scannet1DProcessor
    processor2D      : Scannet2DProcessor
    processor3D      : Scannet3DProcessor
    mesh_subfix      : _vh_clean_2.labels.ply
    seg_subfix       : _vh_clean_2.0.010000.segs.json
    aggre_subfix     : _vh_clean.aggregation.json
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len   : 150
    voxel_size       : 0.02
  
  Scan3R:
    base_dir       : /drive/datasets/Scan3R/
    process_dir    : ${data.process_dir}/Scan3R/
    processor3D    : Scan3R3DProcessor
    processor2D    : Scan3R2DProcessor
    processor1D    : Scan3R1DProcessor
    label_filename : labels.instances.align.annotated.v2.ply
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len : 150
    voxel_size     : 0.02

  MultiScan:
    base_dir       : /media/sayan/Expansion/data/datasets/MultiScan
    process_dir    : ${data.process_dir}/MultiScan
    processor3D    : MultiScan3DProcessor
    processor2D    : MultiScan2DProcessor
    processor1D    : MultiScan1DProcessor
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len : 150
    voxel_size     : 0.02

task: 
  name       : InferenceObjectRetrieval
  InferenceObjectRetrieval:
    val                     : [Scannet]
    modalities              : ['rgb', 'point', 'cad', 'referral']
    scene_modalities        : ['rgb', 'point', 'referral', 'floorplan']
    ckpt_path               : /drive/dumps/multimodal-spaces/runs/release_runs/instance_crossover_scannet+scan3r+multiscan.pth
    

inference_module: ObjectRetrieval

model: 
  name: SceneLevelEncoder
  point:
    embed_dim : 384
  cad:
    embed_dim : 384
  image:
    embed_dim : 1536
  referral:
    embed_dim : 768

  # Only For Unified Encoder
  encoder1D:
    input_dim : 768
  encoder2D :
    input_dim : 1536
  encoder3D:
    input_channels : 3
    d_model        : 512
    conv_layers    : [16, 32, 64, 128, 256]
  out_dim       : 768

dataloader:
  batch_size  : 1
  num_workers : 4
