name: "PreProcess3D"

base_dir : "/drive/dumps/multimodal-spaces"
exp_dir  : ""
  
data:
  sources: []
  process_dir: ${base_dir}/preprocess_feats
  Scannet:
    base_dir         : /drive/datasets/Scannet
    shape_dir        : /drive/datasets/Shapenet/ShapeNetCore.v2
    process_dir      : ${data.process_dir}/Scannet
    chunked_dir      : ${data.process_dir}/Scannet/objects_chunked/
    processor3D      : Scannet3DProcessor
    mesh_subfix      : _vh_clean_2.labels.ply
    seg_subfix       : _vh_clean_2.0.010000.segs.json
    aggre_subfix     : _vh_clean.aggregation.json
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
  
  Scan3R:
    base_dir         : /drive/datasets/Scan3R
    process_dir      : ${data.process_dir}/Scan3R
    chunked_dir      : ${data.process_dir}/Scan3R/objects_chunked/
    processor3D      : Scan3R3DProcessor
    processor2D      : Scan3R2DProcessor
    processor1D      : Scan3R1DProcessor
    label_filename   : labels.instances.align.annotated.v2.ply
    skip_frames      : 1
    avail_modalities : ['point', 'rgb', 'referral']

  ARKitScenes:
    base_dir       : /media/sayan/Expansion/data/datasets/ARKitScenes
    process_dir    : ${data.process_dir}/ARKitScenes/
    chunked_dir    : ${data.process_dir}/ARKitScenes/objects_chunked
    processor3D    : ARKitScenes3DProcessor
    processor2D    : ARKitScenes2DProcessor
    processor1D    : ARKitScenes1DProcessor
    avail_modalities : ['point', 'rgb', 'referral']

  MultiScan:
    base_dir         : /media/sayan/Expansion/data/datasets/MultiScan
    process_dir      : ${data.process_dir}/MultiScan/
    chunked_dir      : ${data.process_dir}/MultiScan/objects_chunked
    processor3D      : Scan3R3DProcessor
    processor2D      : Scan3R2DProcessor
    processor1D      : Scan3R1DProcessor
    avail_modalities : ['point', 'rgb', 'referral']
    
modality_info:
  1D  :
    feature_extractor: 
      model     : BLIP
      ckpt      : https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_large.pth      
      embed_dim : 768
  
  2D  :
    feature_extractor:
      model     : DinoV2
      ckpt      : dinov2_vitg14
      embed_dim : 1536
  
  3D  :
    feature_extractor:
      model      : I2PMAE
      ckpt       : /drive/pretrained-models/pointbind_i2pmae.pt 
      embed_dim  : 384
    
    voxel_size : 0.05
    max_points_per_object : 1024
    min_points_per_object : 50

task: 
  name       : PreprocessMultimodal 
  Preprocess :
    modality : '3D'
    splits   : ['train', 'val']
  
  PreprocessMultimodal :
    processor : MultimodalPreprocessor
    splits    : ['train', 'val']