name: "CrossOver"
rng_seed        : 42
num_gpu         : 1
base_dir        : "/drive/dumps/multimodal-spaces/"
exp_dir         : ""
mode            : "train"
naming_keywords : ['task', 'time', 'all_align']

resume : False

logger :
  name : "wandb"
  entity : "multimodal-spaces"

  
data :
  sources     : []
  process_dir : ${base_dir}/preprocess_feats
  
  Scannet:
    base_dir         : /drive/datasets/Scannet
    shape_dir        : /drive/datasets/Shapenet/ShapeNet_preprocessed/
    process_dir      : ${data.process_dir}/Scannet
    chunked_dir      : ${data.process_dir}/Scannet/objects_chunked
    processor1D      : Scannet1DProcessor
    processor2D      : Scannet2DProcessor
    processor3D      : Scannet3DProcessor
    mesh_subfix      : _vh_clean_2.labels.ply
    seg_subfix       : _vh_clean_2.0.010000.segs.json
    aggre_subfix     : _vh_clean.aggregation.json
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len   : 150
    voxel_size       : 0.02
  
  Scan3R:
    base_dir       : /drive/datasets/Scan3R/
    process_dir    : ${data.process_dir}/Scan3R/
    chunked_dir    : ${data.process_dir}/Scan3R/objects_chunked
    processor3D    : Scan3R3DProcessor
    processor2D    : Scan3R2DProcessor
    processor1D    : Scan3R1DProcessor
    label_filename : labels.instances.align.annotated.v2.ply
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len : 150
    voxel_size     : 0.02

  MultiScan:
    base_dir       : /media/sayan/Expansion/data/datasets/Multiscan
    process_dir    : ${data.process_dir}/MultiScan/
    chunked_dir    : ${data.process_dir}/MultiScan/objects_chunked
    processor3D    : MultiScan3DProcessor
    processor2D    : MultiScan2DProcessor
    processor1D    : MultiScan1DProcessor
    avail_modalities : ['point', 'cad', 'rgb', 'referral']
    max_object_len   : 150
    voxel_size       : 0.02
    
task: 
  name         : UnifiedTrain 
  UnifiedTrain :
    modalities       : ['rgb', 'point', 'cad', 'referral']
    scene_modalities : ['rgb', 'point', 'floorplan', 'referral']
    train            : [Scannet, Scan3R, MultiScan]
    val              : [Scannet, Scan3R, MultiScan]
    object_enc_ckpt  : /drive/dumps/multimodal-spaces/runs/release_runs/instance_crossover_scannet+scan3r+multiscan.pth
    
trainer: UnifiedTrainer

model:
  name: UnifiedEncoder
  point:
    embed_dim : 384
  cad:
    embed_dim : 384
  image:
    embed_dim : 1536
  referral:
    embed_dim : 768

  encoder1D:
    input_dim : 768
  encoder2D:
    input_dim : 1536
  encoder3D:
    input_dim : 512

  out_dim       : 768
  loss          : RetrievalLoss
  base_modality : 'rgb'

dataloader:
  batch_size  : 16
  num_workers : 6

eval:
  train:
    name: RetrievalEval
  val:
    name: RetrievalEval
  save: False

solver:
  gradient_accumulation_steps: 1
  epochs_per_save: 20
  epochs_per_eval: 1
  lr: 1e-3
  grad_norm: 5.0
  epochs: 300
  optim:
    name: 'AdamW'
    args:
      betas: [0.9, 0.98]
  sched:
    name: 'warmup_cosine'
    args:
      warmup_steps: 10
      minimum_ratio: 0.1